# Generated by Django 4.1.1 on 2022-10-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_created=True, verbose_name='Sana: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=128, verbose_name='F.I.SH.')),
                ('slug', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=9, verbose_name='Telefon raqamingiz: +998 ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Homiylik summasi: ')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sarflangan summa: ')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('moderation', 'Moderatsiyada'), ('confirmed', 'Tasdiqlangan'), ('cancel', 'Bekor qilingan')], default='cancel', max_length=128, verbose_name='Status: ')),
                ('sponsor_type', models.CharField(choices=[('physical', 'Jismoniy shaxs'), ('entity', 'Yuridik shaxs')], default='physical', max_length=128, verbose_name='Qaysi turdagi shaxs: ')),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
