# Generated by Django 4.1.1 on 2022-10-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='date_joined',
        ),
    ]
