# Generated by Django 4.1.1 on 2022-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_remove_sponsor_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tashkilot'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Telefon raqamingiz: +998'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sarflangan summa'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('physical', 'Jismoniy shaxs'), ('entity', 'Yuridik shaxs')], default='physical', max_length=128, verbose_name='Qaysi turdagi shaxs'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('moderation', 'Moderatsiyada'), ('confirmed', 'Tasdiqlangan'), ('cancel', 'Bekor qilingan')], default='cancel', max_length=128, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Homiylik summasi'),
        ),
    ]
