# Generated by Django 4.1.1 on 2022-10-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_studentsponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsponsor',
            old_name='price',
            new_name='amount',
        ),
    ]
