# Generated by Django 4.1.1 on 2022-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_price_studentsponsor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
