# Generated by Django 4.1.1 on 2022-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
